In [1]:
import pandas as pd
import numpy as np

In [2]:
movies=pd.read_csv('moviesds.csv')

In [3]:
movies.head(10)

,id,title,vote_average,vote_count,status,release_date,revenue,runtime,adult,backdrop_path,...,original_title,overview,popularity,poster_path,tagline,genres,production_companies,production_countries,spoken_languages,keywords
0,27205,Inception,8.364,34495,Released,2010-07-15,825532764,148,False,/8ZTVqvKDQ8emSGUEMjsS4yHAwrp.jpg,...,Inception,"Cobb, a skilled thief who commits corporate es...",83.952,/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg,Your mind is the scene of the crime.,"Action, Science Fiction, Adventure","Legendary Pictures, Syncopy, Warner Bros. Pict...","United Kingdom, United States of America","English, French, Japanese, Swahili","rescue, mission, dream, airplane, paris, franc..."
1,157336,Interstellar,8.417,32571,Released,2014-11-05,701729206,169,False,/pbrkL804c8yAv3zBZR4QPEafpAR.jpg,...,Interstellar,The adventures of a group of explorers who mak...,140.241,/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg,Mankind was born on Earth. It was never meant ...,"Adventure, Drama, Science Fiction","Legendary Pictures, Syncopy, Lynda Obst Produc...","United Kingdom, United States of America",English,"rescue, future, spacecraft, race against time,..."
2,155,The Dark Knight,8.512,30619,Released,2008-07-16,1004558444,152,False,/nMKdUUepR0i5zn0y1T4CsSB5chy.jpg,...,The Dark Knight,Batman raises the stakes in his war on crime. ...,130.643,/qJ2tW6WMUDux911r6m7haRef0WH.jpg,Welcome to a world without rules.,"Drama, Action, Crime, Thriller","DC Comics, Legendary Pictures, Syncopy, Isobel...","United Kingdom, United States of America","English, Mandarin","joker, sadism, chaos, secret identity, crime f..."
3,19995,Avatar,7.573,29815,Released,2009-12-15,2923706026,162,False,/vL5LR6WdxWPjLPFRLe133jXWsh5.jpg,...,Avatar,"In the 22nd century, a paraplegic Marine is di...",79.932,/kyeqWdyUXW608qlYkRqosgbbJyK.jpg,Enter the world of Pandora.,"Action, Adventure, Fantasy, Science Fiction","Dune Entertainment, Lightstorm Entertainment, ...","United States of America, United Kingdom","English, Spanish","future, society, culture clash, space travel, ..."
4,24428,The Avengers,7.710,29166,Released,2012-04-25,1518815515,143,False,/9BBTo63ANSmhC4e6r62OJFuK2GL.jpg,...,The Avengers,When an unexpected enemy emerges and threatens...,98.082,/RYMX2wcKCBAr24UyPD7xwmjaTn.jpg,Some assembly required.,"Science Fiction, Action, Adventure",Marvel Studios,United States of America,"English, Hindi, Russian","new york city, superhero, shield, based on com..."
5,293660,Deadpool,7.606,28894,Released,2016-02-09,783100000,108,False,/en971MEXui9diirXlogOrPKmsEn.jpg,...,Deadpool,The origin story of former Special Forces oper...,72.735,/zq8Cl3PNIDGU3iWNRoc5nEZ6pCe.jpg,Witness the beginning of a happy ending.,"Action, Adventure, Comedy","20th Century Fox, The Donners' Company, Genre ...",United States of America,English,"superhero, anti hero, mercenary, based on comi..."
6,299536,Avengers: Infinity War,8.255,27713,Released,2018-04-25,2052415039,149,False,/mDfJG3LC3Dqb67AZ52x3Z0jU0uB.jpg,...,Avengers: Infinity War,As the Avengers and their allies have continue...,154.340,/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg,An entire universe. Once and for all.,"Adventure, Action, Science Fiction",Marvel Studios,United States of America,"English, Xhosa","sacrifice, magic, superhero, based on comic, s..."
7,550,Fight Club,8.438,27238,Released,1999-10-15,100853753,139,False,/hZkgoQYus5vegHoetLkCJzb17zJ.jpg,...,Fight Club,A ticking-time-bomb insomniac and a slippery s...,69.498,/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg,Mischief. Mayhem. Soap.,Drama,"Regency Enterprises, Fox 2000 Pictures, Taurus...",United States of America,English,"dual identity, rage and hate, based on novel o..."
8,118340,Guardians of the Galaxy,7.906,26638,Released,2014-07-30,772776600,121,False,/uLtVbjvS1O7gXL8lUOwsFOH4man.jpg,...,Guardians of the Galaxy,"Light years from Earth, 26 years after being a...",33.255,/r7vmZjiyZw9rpJMQJdXpjgiCOk9.jpg,All heroes start somewhere.,"Action, Science Fiction, Adventure",Marvel Studios,United States of America,English,"spacecraft, based on comic, space, orphan, adv..."
9,680,Pulp Fiction,8.488,25893,Released,1994-09-10,213900000,154,False,/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg,...,Pulp Fiction,"A burger-loving hit man, his philosophical par...",74.862,/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg,Just because you are a character doesn't mean ...,"Thriller, Crime","Miramax, A Band Apart, Jersey Films",United States of America,"English, Spanish, French","drug dealer, boxer, massage, stolen money, bri..."

In [4]:
movies.describe()

,id,vote_average,vote_count,revenue,runtime,budget,popularity
count,1.068597e+06,1.068597e+06,1.068597e+06,1.068597e+06,1.068597e+06,1.068597e+06,1.068597e+06
mean,7.013812e+05,1.985565e+00,2.007031e+01,7.113737e+05,4.924788e+01,2.793325e+05,1.285156e+00
std,3.753771e+05,3.066278e+00,3.284578e+02,1.794087e+07,6.206482e+01,5.063786e+06,7.821327e+00
min,2.000000e+00,0.000000e+00,0.000000e+00,-1.200000e+01,-2.800000e+01,0.000000e+00,0.000000e+00
25%,3.905210e+05,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,6.000000e-01
50%,7.038130e+05,0.000000e+00,0.000000e+00,0.000000e+00,2.600000e+01,0.000000e+00,6.000000e-01
75%,1.030912e+06,5.000000e+00,1.000000e+00,0.000000e+00,9.000000e+01,0.000000e+00,8.850000e-01
max,1.321371e+06,1.000000e+01,3.449500e+04,3.000000e+09,1.440000e+04,9.000000e+08,2.994357e+03

In [5]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1068597 entries, 0 to 1068596
Data columns (total 24 columns):
 #   Column                Non-Null Count    Dtype
---  ------                --------------    -----
 0   id                    1068597 non-null  int64
 1   title                 1068585 non-null  object
 2   vote_average          1068597 non-null  float64
 3   vote_count            1068597 non-null  int64
 4   status                1068597 non-null  object
 5   release_date          919961 non-null   object
 6   revenue               1068597 non-null  int64
 7   runtime               1068597 non-null  int64
 8   adult                 1068597 non-null  bool
 9   backdrop_path         292281 non-null   object
 10  budget                1068597 non-null  int64
 11  homepage              115143 non-null   object
 12  imdb_id               588307 non-null   object
 13  original_language     1068597 non-null  object
 14  original_title        1068585 non-null  object
 15  overview              867546 non-null   object
 16  popularity            1068597 non-null  float64
 17  poster_path           752760 non-null   object
 18  tagline               152245 non-null   object
 19  genres                658265 non-null   object
 20  production_companies  495484 non-null   object
 21  production_countries  614849 non-null   object
 22  spoken_languages      630610 non-null   object
 23  keywords              299609 non-null   object
dtypes: bool(1), float64(2), int64(5), object(16)
memory usage: 188.5+ MB

In [6]:
movies.isnull().sum()

id                           0
title                       12
vote_average                 0
vote_count                   0
status                       0
release_date            148636
revenue                      0
runtime                      0
adult                        0
backdrop_path           776316
budget                       0
homepage                953454
imdb_id                 480290
original_language            0
original_title              12
overview                201051
popularity                   0
poster_path             315837
tagline                 916352
genres                  410332
production_companies    573113
production_countries    453748
spoken_languages        437987
keywords                768988
dtype: int64

In [7]:
movies=movies[['id','title','overview','genres','keywords']]
movies

,id,title,overview,genres,keywords
0,27205,Inception,"Cobb, a skilled thief who commits corporate es...","Action, Science Fiction, Adventure","rescue, mission, dream, airplane, paris, franc..."
1,157336,Interstellar,The adventures of a group of explorers who mak...,"Adventure, Drama, Science Fiction","rescue, future, spacecraft, race against time,..."
2,155,The Dark Knight,Batman raises the stakes in his war on crime. ...,"Drama, Action, Crime, Thriller","joker, sadism, chaos, secret identity, crime f..."
3,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","Action, Adventure, Fantasy, Science Fiction","future, society, culture clash, space travel, ..."
4,24428,The Avengers,When an unexpected enemy emerges and threatens...,"Science Fiction, Action, Adventure","new york city, superhero, shield, based on com..."
...,...,...,...,...,...
1068592,713630,Drifts,Milling about...,Documentary,NaN
1068593,713631,ANIMAL CONDENSED>>ANIMAL EXPANDED#2,The director couldn’t have anticipated the cor...,Science Fiction,NaN
1068594,713634,Southern Journey (Revisited),Traversing the back-roads of the Southern Unit...,"Documentary, Music",NaN
1068595,713635,La Dame de chez Maxim,"Doctor Petypon, a respectable doctor, partied ...",Comedy,theater play
1068596,1321103,Black Ag,A Black scientist brings together local Black ...,NaN,NaN

In [8]:
movies.isnull().sum()

id               0
title           12
overview    201051
genres      410332
keywords    768988
dtype: int64

In [9]:
movies.dropna(subset=['title'], inplace=True)

In [10]:
movies.isnull().sum()

id               0
title            0
overview    201043
genres      410325
keywords    768977
dtype: int64

In [11]:
movies['tag']=movies['genres']+movies['keywords']+movies['overview']

In [12]:
movies=movies.drop(['overview','genres','keywords'],axis=1)

In [13]:
movies['tag'] = movies['tag'].fillna('nothing')

In [14]:
movies=movies[:20000]
movies.shape

(20000, 3)

In [15]:
from sklearn.feature_extraction.text import CountVectorizer

In [16]:
cv=CountVectorizer(max_features=20000,stop_words='english')

In [17]:
cv

CountVectorizer(max_features=20000, stop_words='english')

In [18]:
vector=cv.fit_transform(movies['tag'].values.astype('U')).toarray()

In [19]:
vector.shape

(20000, 20000)

In [20]:
from sklearn.metrics.pairwise import cosine_similarity

In [21]:
similarity=cosine_similarity(vector)

In [44]:
distance=sorted(list(enumerate(similarity[2])),reverse=True,key=lambda vector:vector[1])

In [46]:
for i in distance[0:5]:
    print(movies.iloc[i[0]].title)

The Dark Knight
Batman
Batman: Under the Red Hood
Batman Begins
Batman: Mask of the Phantasm

In [84]:
def recommand(movie):
    index=movies[movies['title']==movie].index[0]
    distance=sorted(list(enumerate(similarity[index])),reverse=True,key=lambda vector:vector[1])
    for i in distance[0:15]:
        print(movies.iloc[i[0]].title)

In [86]:
recommand("Thor")

Thor
Thor: Love and Thunder
Team Thor
Thor: Ragnarok
Thor: The Dark World
Eternals
Captain Marvel
Thor: Tales of Asgard
Hulk vs. Thor
Iron Man 3
Doctor Strange
Guardians of the Galaxy Vol. 2
Hulk Vs.
The Incredible Hulk Returns
Captain America: Civil War

In [90]:
import pickle

In [92]:
pickle.dump(movies,open('movies_list.pkl','wb'))

In [94]:
pickle.dump(similarity,open('similarity.pkl','wb'))

In [96]:
pickle.load(open('movies_list.pkl','rb'))

,id,title,tag
0,27205,Inception,"Action, Science Fiction, Adventurerescue, miss..."
1,157336,Interstellar,"Adventure, Drama, Science Fictionrescue, futur..."
2,155,The Dark Knight,"Drama, Action, Crime, Thrillerjoker, sadism, c..."
3,19995,Avatar,"Action, Adventure, Fantasy, Science Fictionfut..."
4,24428,The Avengers,"Science Fiction, Action, Adventurenew york cit..."
...,...,...,...
19995,265339,Ana and Bruno,"Animation, Adventure, Familyadult animationAna..."
19996,28894,Rancho Notorious,nothing
19997,40089,The Best Job in the World,"Comedy, Dramaghetto, big family, delinquency, ..."
19998,850871,Sayen,"Action, Adventuremapuche, ecologism, ecosystem..."
19999,64397,"Basic Sanitation, the Movie",nothing